//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamlBinding.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamlBinding.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}.{1}, type={2}.
        /// </summary>
        public static string BindingEntry_TargetText {
            get {
                return ResourceManager.GetString("BindingEntry.TargetText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; cannot be assigned to property {1}.
        /// </summary>
        public static string Description_BadValueAtTransfer {
            get {
                return ResourceManager.GetString("Description.BadValueAtTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert from type &apos;{0}&apos; to &apos;{1}&apos;. Consider setting a converter on the binding..
        /// </summary>
        public static string Description_CannotCreateDefaultValueConverter {
            get {
                return ResourceManager.GetString("Description.CannotCreateDefaultValueConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} property not found on type {1}.
        /// </summary>
        public static string Description_ClrReplaceItem {
            get {
                return ResourceManager.GetString("Description.ClrReplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding Path.
        /// </summary>
        public static string Header_BindingPath {
            get {
                return ResourceManager.GetString("Header.BindingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Header_Code {
            get {
                return ResourceManager.GetString("Header.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Header_Count {
            get {
                return ResourceManager.GetString("Header.Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Context Type.
        /// </summary>
        public static string Header_DataContextType {
            get {
                return ResourceManager.GetString("Header.DataContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Header_Description {
            get {
                return ResourceManager.GetString("Header.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Header_Target {
            get {
                return ResourceManager.GetString("Header.Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML Binding Failures.
        /// </summary>
        public static string ToolWindow_Title {
            get {
                return ResourceManager.GetString("ToolWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML Binding Failures (loading).
        /// </summary>
        public static string ToolWindow_TitleLoading {
            get {
                return ResourceManager.GetString("ToolWindow.TitleLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off,Critical,Error,Warning,Information,Verbose,Activity,All.
        /// </summary>
        public static string TraceLevels {
            get {
                return ResourceManager.GetString("TraceLevels", resourceCulture);
            }
        }
    }
}
