//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XamlBinding.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("XamlBinding.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML Binding Failures.
        /// </summary>
        public static string _100 {
            get {
                return ResourceManager.GetString("100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to convert value &apos;{0}&apos; to the target type. The fallback value will be used if it&apos;s available.{1}.
        /// </summary>
        public static string Description_BadConverterAtTransfer {
            get {
                return ResourceManager.GetString("Description.BadConverterAtTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; cannot be assigned to property {1}, type={2}.
        /// </summary>
        public static string Description_BadValueAtTransfer {
            get {
                return ResourceManager.GetString("Description.BadValueAtTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert from type &apos;{0}&apos; to &apos;{1}&apos;. Consider setting a converter on the binding..
        /// </summary>
        public static string Description_CannotCreateDefaultValueConverter {
            get {
                return ResourceManager.GetString("Description.CannotCreateDefaultValueConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to get value.{0}.
        /// </summary>
        public static string Description_CannotGetClrRawValue {
            get {
                return ResourceManager.GetString("Description.CannotGetClrRawValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} property not found on type {1}.
        /// </summary>
        public static string Description_ClrReplaceItem {
            get {
                return ResourceManager.GetString("Description.ClrReplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve value due to missing information..
        /// </summary>
        public static string Description_MissingInfo {
            get {
                return ResourceManager.GetString("Description.MissingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find governing FrameworkElement or FrameworkContentElement for target element..
        /// </summary>
        public static string Description_NoMentor {
            get {
                return ResourceManager.GetString("Description.NoMentor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find source: {0}.
        /// </summary>
        public static string Description_NoSource {
            get {
                return ResourceManager.GetString("Description.NoSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve value and no fallback value exists, using the default value instead..
        /// </summary>
        public static string Description_NoValueToTransfer {
            get {
                return ResourceManager.GetString("Description.NoValueToTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot retrieve value from a null data item. This could happen when the binding is detached or when binding to a Nullable type that has no value..
        /// </summary>
        public static string Description_NullDataItem {
            get {
                return ResourceManager.GetString("Description.NullDataItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; property not found for &apos;{1}&apos; because data item is null. This could happen because the data provider has not produced any data yet..
        /// </summary>
        public static string Description_NullItem {
            get {
                return ResourceManager.GetString("Description.NullItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding Path.
        /// </summary>
        public static string Header_BindingPath {
            get {
                return ResourceManager.GetString("Header.BindingPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Header_Code {
            get {
                return ResourceManager.GetString("Header.Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Header_Count {
            get {
                return ResourceManager.GetString("Header.Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Context Type.
        /// </summary>
        public static string Header_DataContextType {
            get {
                return ResourceManager.GetString("Header.DataContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Header_Description {
            get {
                return ResourceManager.GetString("Header.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        public static string Header_Target {
            get {
                return ResourceManager.GetString("Header.Target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target Type.
        /// </summary>
        public static string Header_TargetType {
            get {
                return ResourceManager.GetString("Header.TargetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For new failures.
        /// </summary>
        public static string OptionsCategoryForNewFailures {
            get {
                return ResourceManager.GetString("OptionsCategoryForNewFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash the Visual Studio window whenever a failure is added to the list.
        /// </summary>
        public static string OptionsDescriptionFlashWindow {
            get {
                return ResourceManager.GetString("OptionsDescriptionFlashWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plays a notification sound whenever a failure is added to the list.
        /// </summary>
        public static string OptionsDescriptionPlaySound {
            get {
                return ResourceManager.GetString("OptionsDescriptionPlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the XAML Binding Failures tool window pane when there is a new error.
        /// </summary>
        public static string OptionsDescriptionShowPane {
            get {
                return ResourceManager.GetString("OptionsDescriptionShowPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash window.
        /// </summary>
        public static string OptionsNameFlashWindow {
            get {
                return ResourceManager.GetString("OptionsNameFlashWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play sound.
        /// </summary>
        public static string OptionsNamePlaySound {
            get {
                return ResourceManager.GetString("OptionsNamePlaySound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show tool window pane.
        /// </summary>
        public static string OptionsNameShowPane {
            get {
                return ResourceManager.GetString("OptionsNameShowPane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML Binding Failures.
        /// </summary>
        public static string ToolWindow_Title {
            get {
                return ResourceManager.GetString("ToolWindow.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XAML Binding Failures (loading).
        /// </summary>
        public static string ToolWindow_TitleLoading {
            get {
                return ResourceManager.GetString("ToolWindow.TitleLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off,Critical,Error,Warning,Information,Verbose,Activity,All.
        /// </summary>
        public static string TraceLevels {
            get {
                return ResourceManager.GetString("TraceLevels", resourceCulture);
            }
        }
    }
}
